CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
# Turn on logging, and set ZMK logging to debug output
CONFIG_ZMK_USB_LOGGING=n

CONFIG_ZMK_DISPLAY=y

CONFIG_ZMK_BLE_MOUSE_REPORT_QUEUE_SIZE=1
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_CTLR_CONN_RSSI=y
CONFIG_BT_CTLR_TX_PWR_DYNAMIC_CONTROL=y
CONFIG_BT_CTLR_PHY_2M=y
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6
CONFIG_BT_TPS=y
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

CONFIG_PAW3222=y
CONFIG_ZMK_INPUT_PROCESSOR_REPORT_RATE_LIMIT=y
CONFIG_ZMK_INPUT_PROCESSOR_REPORT_RATE_LIMIT_DEFAULT=2


# CONFIG_PMW3610_LOG_LEVEL_DBG=y
