CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=10
CONFIG_PMW3610_REPORT_INTERVAL_MIN=0
CONFIG_PMW3610_SMART_ALGORITHM=y
CONFIG_PMW3610_SQUAL_LOG=n
CONFIG_PMW3610_SQUAL_LOG_INTERVAL=250
CONFIG_PMW3610_ANTI_WARP=y
CONFIG_PMW3610_ANTI_WARP_THRES=100
CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=35
CONFIG_PMW3610_REST2_SAMPLE_TIME_MS=65
CONFIG_PMW3610_REST3_SAMPLE_TIME_MS=250
CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=2500
CONFIG_PMW3610_REST1_DOWNSHIFT_TIME_MS=15000
CONFIG_PMW3610_REST2_DOWNSHIFT_TIME_MS=150000
CONFIG_PMW3610_IGNORE_FIRST_N=15
CONFIG_PMW3610_IGNORE_AFTER_REST=n
